export const entregadores = [
    {
        "id":1,
        "nome":"Carlos",
        "CNH":"1111111111",
        "imagemCNH":"www.cnh.br",
        "veiculo":"Carro",
        "placa":"abc-1234",
        "capacidade":"30kg"
    },
    {
        "id":2,
        "nome":"Fernando",
        "CNH":"2222222222",
        "imagemCNH":"www.cnh.br",
        "veiculo":"moto",
        "placa":"def-1234",
        "capacidade":"10kg"
    },
    {
        "id":3,
        "nome":"Igor",
        "CNH":"333333333",
        "imagemCNH":"www.cnh.br",
        "veiculo":"van",
        "placa":"ghi-1234",
        "capacidade":"50kg"
    }
]